# Linear systems: Some basic related to matrices in Python and example of Gaussian Elimination (two by two matrix) in floating point arithmetic (September 30, 2022)

30/09/2022

Francesca Mazzia

 Creative Commons Attribuzione-Non commerciale-Non Opere Derivate 2.5 Italy License http://creativecommons.org/licenses/by-nc-nd/2.5/it/

### Matrices and Vectors

In [37]:
import numpy as np
A = np.array([3., 5., 6.]) # we use numpy
print(A)

[3. 5. 6.]


In [38]:
A.size

3

no difference with array between row vectors and column vectors

In [39]:
A[0] + A[1] + A[2]

14.0

In [40]:
np.sum(A)

14.0

In [41]:
np.min(A)

3.0

In [42]:
np.argmin(A)

0

In [43]:
A[np.argmin(A)]

3.0

In [44]:
np.argmax(A)

2

In [45]:
A[np.argmax(A)]

6.0

In [46]:
A=np.array([[  3.,   5.,   7.],
           [  8.,   9.,  10.],
           [  2.,   3.,   5.]])
A

array([[ 3.,  5.,  7.],
       [ 8.,  9., 10.],
       [ 2.,  3.,  5.]])

In [47]:
A[0,0]

3.0

In [48]:
A[:,0]

array([3., 8., 2.])

In [49]:
A[0,]

array([3., 5., 7.])

In [50]:
A[1:3,1:3]

array([[ 9., 10.],
       [ 3.,  5.]])

example of use of linspace 

In [51]:
import numpy as np
x = np.linspace(-50,-1,5)
print(x)
type(x)
np.size(x)

[-50.   -37.75 -25.5  -13.25  -1.  ]


5

In [52]:
x=1e2
x

100.0

Example of random matrices

In [53]:
# np.random.rand : uniform distribution
A = np.random.rand(3,4)*10
print(A)

[[0.1499289  5.52383763 7.68266913 1.86699044]
 [3.87463659 3.99855111 8.51319579 7.85232168]
 [1.86106909 0.32054897 9.17247377 6.49633364]]


In [54]:

# square matrix with integer elements
A = np.random.randint(10,size=(3,3))
print(A)

[[0 1 0]
 [9 6 1]
 [3 5 9]]


In [55]:
# Elements of the matrix with column and row index
print(A[0,0])
print(A[1,1])
print(A[2,2])

0
6
9


In [56]:
print(type(A))

<class 'numpy.ndarray'>


In [57]:
C=np.array([[0,0,1,0,1],[1,0,0,0,1],[0,0,0,1,1],[0,1,0,0,1],[1,1,1,1,0]])
C

array([[0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0]])

Trasposta

In [58]:
print('transpose\n',C.T)

transpose
 [[0 1 0 0 1]
 [0 0 0 1 1]
 [1 0 0 0 1]
 [0 0 1 0 1]
 [1 1 1 1 0]]


In [59]:
np.dot(C,C)

array([[1, 1, 1, 2, 1],
       [1, 1, 2, 1, 1],
       [1, 2, 1, 1, 1],
       [2, 1, 1, 1, 1],
       [1, 1, 1, 1, 4]])

Product row by column of a matrix

In [60]:
print(np.dot(A,A))
print(A@A)
# this is not the correct operator
print(A*A)
print(A)

[[ 9  6  1]
 [57 50 15]
 [72 78 86]]
[[ 9  6  1]
 [57 50 15]
 [72 78 86]]
[[ 0  1  0]
 [81 36  1]
 [ 9 25 81]]
[[0 1 0]
 [9 6 1]
 [3 5 9]]


In [61]:
U=np.triu(A)   # triangula part of A
print(type(U)) # 
print(U)

<class 'numpy.ndarray'>
[[0 1 0]
 [0 6 1]
 [0 0 9]]


In [62]:
A.shape  # numero di righe e colonne

(3, 3)

In [63]:
A.ndim  # dimensione della matrice, possiamo avere array a piu' dimensioni

2

In [64]:
O = np.zeros( (3,3) ) # matrice nulla
print(O)
print(type(O))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [65]:
I = np.eye(3) # matrice identità
print(type(I))
print(I)

<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
d = np.diag(np.array([1, 2, 3, 4])) # diagonal matrix
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [67]:
narray = np.arange(1,10,2) # arange array
print(narray)

[1 3 5 7 9]


In [68]:
B = np.empty((3,4) ) # empty array
print(B)

[[0.1499289  5.52383763 7.68266913 1.86699044]
 [3.87463659 3.99855111 8.51319579 7.85232168]
 [1.86106909 0.32054897 9.17247377 6.49633364]]


In [69]:
C=np.empty((3,5))
print(C)

[[0.         0.         0.4472136  0.0531494  0.18257419]
 [0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]


In [70]:
a = np.arange(10) 
print(a)
print('--- change the order ---')
print(a[::-1])      # ordine inverso

[0 1 2 3 4 5 6 7 8 9]
--- change the order ---
[9 8 7 6 5 4 3 2 1 0]


In [77]:
# computational time without loop
import time
n = 1000000
a = np.arange(n)
t1=time.process_time()
b = a + 1  
t2=time.process_time()
t2a=time.process_time()-t1
print(t2a)

0.005125999999999964


In [78]:
# computational time with loop
l = range(n)
b = np.empty(n)
t1=time.process_time()
for i in l: 
    b[i]=i+1 
t2b=time.process_time()-t1
print(t2b)

0.1524310000000002


In [79]:
 a = np.array([1, 2, 3, 4])
 b = np.array([4, 2, 2, 4])
 a == b


array([False,  True, False,  True])

In [80]:
a > b


array([False, False,  True, False])

In [81]:
 np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [82]:
np.sin(a[0])

0.8414709848078965

linalg.solve for the solution of one linear system

In [ ]:
A = np.random.rand(3,3)
b = np.array([1,2,3])
x = np.linalg.solve(A,b)
print(x)
print(type(x))

In [ ]:
print('type of A =',type(A))
print('residual =', np.dot(A,x)-b) 

In [ ]:
# remember: the array vector does not are row vectors or column vectors
y = x.T
print(y.shape)

print('A*x = ',A*x)
print('A*y-A*x =', A*y-A*x)
print(' A = ', A)
print(' x = ', x)
print('A[:,0]*x[0] = ', A[:,0]*x[0])
print('A[:,1]*x[1] =', A[:,1]*x[1])
print( 'A[:,2]*x[2] =',A[:,2]*x[2])


Gaussian elimination in floating point arithmetic

In [ ]:
import numpy as np
ex = 2
par = 1e-17 # 10^(-17)
if ex==1:
# Example 1
 A=np.array( [[par,1.],[1., 2.]])
 b= np.array([[1.],[3.]])
else:
# Example 2
 A=np.array( [[10.,1./par],[1., 2.]])
 b= np.array([[1./par],[3.]])


print(A)
print(b)

[[1.e+01 1.e+17]
 [1.e+00 2.e+00]]
[[1.e+17]
 [3.e+00]]


In [ ]:
Ah = np.hstack((A,b))
print(Ah)

[[1.e+01 1.e+17 1.e+17]
 [1.e+00 2.e+00 3.e+00]]


In [ ]:
Ah[1,:]=Ah[1,:]-Ah[0,:]*(Ah[1,0]/Ah[0,0])
print(Ah)

[[ 1.e+01  1.e+17  1.e+17]
 [ 0.e+00 -1.e+16 -1.e+16]]


solve the upper triangular system

In [ ]:
xg = np.zeros((2,1))
xg[1]= Ah[1,2]/Ah[1,1]
xg[0]= (Ah[0,2]-Ah[0,1]*xg[1])/Ah[0,0]
print('Solution after Gaussian Elimination \n',xg)

Solution after Gaussian Elimination 
 [[1.6]
 [1. ]]


In [ ]:
x = np.linalg.solve(A,b)
print('linalg solve algorithm \n',x)

linalg solve algorithm 
 [[0.]
 [1.]]


Solution of a lower triangular linear system:

In [ ]:
#definiamo la function
import numpy as np

def solL(L,b):
    """
    Solution of a lower triangular system,
    implementation by row 
    INPUT  =matrix L, known term b
    OUTPUT =solution x
    
    """
    (n,m) = np.shape(b)
    x = np.zeros((n,1))
    x[0]=b[0]/L[0,0]
    for i in range(1,n):
        x[i]=(b[i] - np.dot(L[i,0:i],x[0:i]))/L[i,i]
    return x

n=50
L  = np.tril(np.random.rand(n,n))
xt = np.ones((n,1))
b  = np.dot(L,xt)
x  = solL(L,b)
print('x')
print(x)
print('absolute error')
print( abs(x-xt))