# ORTHOGONALITY

02/04/2020

Francesca Mazzia

license: Creative Commons non-commercial not derivative works - 2.5 Italy License http://creativecommons.org/licenses/by-nc-nd/2.5/it/

###  Orthogonal  matrices

In [28]:
import scipy as sp
import numpy as np
import  scipy.stats as sst

M = sst.ortho_group.rvs(dim=3)
print('Orthogonal Random matrix: \n',M)

Orthogonal Random matrix: 
 [[ 0.28221546  0.8817625  -0.37795413]
 [-0.50468985 -0.19858717 -0.84014956]
 [-0.81586922  0.42785281  0.38897222]]


In [29]:
print('dot product: \n', np.dot(M,M.T))
# M M^T = I identity matrix  M^T is the inverse of an orthogonal matrix (orthogonal matrix square matrix)

dot product: 
 [[ 1.00000000e+00  2.70321765e-16  9.84913573e-17]
 [ 2.70321765e-16  1.00000000e+00 -1.09606714e-16]
 [ 9.84913573e-17 -1.09606714e-16  1.00000000e+00]]


In [30]:
print('dot product: \n', np.dot(M.T,M))
# M^T M = I identity matrix

dot product: 
 [[ 1.00000000e+00 -1.71589246e-16  1.61163647e-16]
 [-1.71589246e-16  1.00000000e+00  4.12834834e-17]
 [ 1.61163647e-16  4.12834834e-17  1.00000000e+00]]


In [31]:
print('Determinant: \n',sp.linalg.det(M)) # det = -1 or det = 1

Determinant: 
 0.9999999999999999


### Generic random matrix
Uniform distribution 

In [32]:
A= np.random.rand(5,3)
print('Generic Random matrix: \n',A)

Generic Random matrix: 
 [[0.77661593 0.86764824 0.10196484]
 [0.95968108 0.9530668  0.91960723]
 [0.23307905 0.49257159 0.21478714]
 [0.65325955 0.94840023 0.55348169]
 [0.52467483 0.26474296 0.20296741]]


In [33]:
rk=np.linalg.matrix_rank(A)
print('Rank of A:', rk)

Rank of A: 3


the vectors are not orthogonal

In [34]:
print(np.dot(A.T,A)) # to check orthogonality of columns

[[2.28047763 2.46173321 1.47983865]
 [2.46173321 2.87332841 1.64937113]
 [1.47983865 1.64937113 1.24974555]]


In [35]:
print(np.dot(A,A.T))

[[1.36634261 1.66599796 0.63029251 1.38664524 0.65787014]
 [1.66599796 2.67500155 0.89065498 2.03979536 0.94248853]
 [0.63029251 0.89065498 0.34308613 0.73829687 0.29629036]
 [1.38664524 2.03979536 0.73829687 1.63255302 0.70616987]
 [0.65787014 0.94248853 0.29629036 0.70616987 0.38656828]]


to orthogonalize it we use the Gram-Schmidt procedure on a set of linearly independent vectors columns of a matrix

In [36]:
def Gram_Schmidt(X):
    (m,n) = X.shape
    U = np.zeros((m,n))
    R = np.zeros((n,n))
    for i in range(n):#ciclo sulle colonne, vettori linearmente indipendenti
        U[:,i] = X[:,i]
        for j in range(i):
            R[j,i] = np.inner(X[:,i], U[:,j])
            U[:,i] = U[:,i] - R[j,i]*U[:,j]
        R[i,i]= np.linalg.norm(U[:,i],2)   
        U[:,i] = U[:,i]/R[i,i] # il vettori ortonormali
    return (U,R)

In [37]:
# l'algoritmo funziona se partiamo da un insieme di vettori linearmente indipendenti
import numpy as np
A = np.array( [[1, 0, 0, 1 ],[0,0,1,-1],[4,0,1,-3]])
A=A.T
A

array([[ 1,  0,  4],
       [ 0,  0,  0],
       [ 0,  1,  1],
       [ 1, -1, -3]])

In [38]:
(U,R) = Gram_Schmidt(A)
print('U=',U)
print('R=',R)


U= [[ 0.70710678  0.40824829  0.57735027]
 [ 0.          0.          0.        ]
 [ 0.          0.81649658 -0.57735027]
 [ 0.70710678 -0.40824829 -0.57735027]]
R= [[ 1.41421356 -0.70710678  0.70710678]
 [ 0.          1.22474487  3.67423461]
 [ 0.          0.          3.46410162]]


In [39]:
print(np.dot(U.T,U))# the columns are an  orthonormal set

[[ 1.00000000e+00 -1.25760346e-16  1.66533454e-16]
 [-1.25760346e-16  1.00000000e+00 -2.22044605e-16]
 [ 1.66533454e-16 -2.22044605e-16  1.00000000e+00]]


In [40]:
print(np.dot(U,U.T)) # we have not the identity because the rows are not an orthonormal set

[[ 1.00000000e+00  0.00000000e+00 -1.72174929e-16 -9.09009624e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.72174929e-16  0.00000000e+00  1.00000000e+00 -1.22556038e-16]
 [-9.09009624e-17  0.00000000e+00 -1.22556038e-16  1.00000000e+00]]


In [41]:
A = np.array( [[1, 0, 0, 1 ],[0,0,1,-1],[4,0,1,3]])
A=A.T
print(A)
(U,R) = Gram_Schmidt(A)
print(U)
print(R)

[[ 1  0  4]
 [ 0  0  0]
 [ 0  1  1]
 [ 1 -1  3]]
[[ 0.70710678  0.40824829  0.80949051]
 [ 0.          0.          0.        ]
 [ 0.          0.81649658  0.231283  ]
 [ 0.70710678 -0.40824829  0.53966034]]
[[ 1.41421356e+00 -7.07106781e-01  4.94974747e+00]
 [ 0.00000000e+00  1.22474487e+00  1.22474487e+00]
 [ 0.00000000e+00  0.00000000e+00  1.44008380e-15]]


In [42]:
print(np.dot(U.T,U))

[[ 1.00000000e+00 -1.25760346e-16  9.53993717e-01]
 [-1.25760346e-16  1.00000000e+00  2.98999487e-01]
 [ 9.53993717e-01  2.98999487e-01  1.00000000e+00]]


In [43]:
rk=np.linalg.matrix_rank(A)
print('Rank of A:', rk)

Rank of A: 2


In [44]:
B = np.random.rand(3,3)
(UB,RB) = Gram_Schmidt(B)
print('UB \n',UB)
print('RB \n',RB)

UB 
 [[ 0.18554808  0.84418917  0.5029081 ]
 [ 0.76847242 -0.44362087  0.46114062]
 [ 0.61239044  0.30090725 -0.73104909]]
RB 
 [[0.75676319 1.00884127 0.74603203]
 [0.         0.44173659 0.62821268]
 [0.         0.         0.34580781]]


In [45]:
print(np.dot(UB.T,UB))

[[ 1.00000000e+00 -2.12934291e-16  1.80092006e-16]
 [-2.12934291e-16  1.00000000e+00  9.46153821e-17]
 [ 1.80092006e-16  9.46153821e-17  1.00000000e+00]]


In [46]:
print(np.dot(UB,UB.T))

[[ 1.00000000e+00 -2.92282389e-17 -1.58199671e-16]
 [-2.92282389e-17  1.00000000e+00 -1.12109013e-17]
 [-1.58199671e-16 -1.12109013e-17  1.00000000e+00]]


In [47]:
print('B \n',B)
print('B-np.dot(UB,RB) \n', B-np.dot(UB,RB))

B 
 [[0.14041596 0.5600978  0.8426647 ]
 [0.58155164 0.57930312 0.45408282]
 [0.46343455 0.75072649 0.39309415]]
B-np.dot(UB,RB) 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


To generate an orthogonal basis we use the QR factorization

In [48]:
(Q,R)=np.linalg.qr(B)
print('Q: \n',Q)
print('R: \n',R)

Q: 
 [[-0.18554808  0.84418917 -0.5029081 ]
 [-0.76847242 -0.44362087 -0.46114062]
 [-0.61239044  0.30090725  0.73104909]]
R: 
 [[-0.75676319 -1.00884127 -0.74603203]
 [ 0.          0.44173659  0.62821268]
 [ 0.          0.         -0.34580781]]


In [49]:
print(UB)
print(RB)

[[ 0.18554808  0.84418917  0.5029081 ]
 [ 0.76847242 -0.44362087  0.46114062]
 [ 0.61239044  0.30090725 -0.73104909]]
[[0.75676319 1.00884127 0.74603203]
 [0.         0.44173659 0.62821268]
 [0.         0.         0.34580781]]


In [50]:
(Q,R)=np.linalg.qr(A)
print('Q: \n',Q)
print('R: \n',R)

Q: 
 [[-0.70710678 -0.40824829  0.09360856]
 [-0.          0.          0.98676862]
 [-0.         -0.81649658 -0.09360856]
 [-0.70710678  0.40824829 -0.09360856]]
R: 
 [[-1.41421356e+00  7.07106781e-01 -4.94974747e+00]
 [ 0.00000000e+00 -1.22474487e+00 -1.22474487e+00]
 [ 0.00000000e+00  0.00000000e+00  2.56704923e-16]]


In [52]:
(U,R) = Gram_Schmidt(A)
print(U)
print(R)

[[ 0.70710678  0.40824829  0.80949051]
 [ 0.          0.          0.        ]
 [ 0.          0.81649658  0.231283  ]
 [ 0.70710678 -0.40824829  0.53966034]]
[[ 1.41421356e+00 -7.07106781e-01  4.94974747e+00]
 [ 0.00000000e+00  1.22474487e+00  1.22474487e+00]
 [ 0.00000000e+00  0.00000000e+00  1.44008380e-15]]


In [53]:
print(np.dot(Q.T,Q))

[[ 1.00000000e+00 -8.65080346e-17  2.77555756e-17]
 [-8.65080346e-17  1.00000000e+00 -3.46944695e-16]
 [ 2.77555756e-17 -3.46944695e-16  1.00000000e+00]]


In [54]:
import scipy.linalg as spl
[Qp,Rp,Pp]=spl.qr(A,pivoting=True)
print(Qp)
print(Rp)
print(Pp)

[[-0.78446454 -0.22645541  0.52325685  0.24399919]
 [-0.          0.         -0.422619    0.90630744]
 [-0.19611614 -0.79259392 -0.52325685 -0.24399919]
 [-0.58834841  0.56613852 -0.52325685 -0.24399919]]
[[-5.09901951e+00  3.92232270e-01 -1.37281295e+00]
 [ 0.00000000e+00 -1.35873244e+00  3.39683110e-01]
 [ 0.00000000e+00  0.00000000e+00  9.34388670e-17]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]
[2 1 0]


In [27]:
(Q,R)=np.linalg.qr(A)
print('Q: \n',Q)
print('R: \n',R)

Q: 
 [[-0.70710678 -0.40824829  0.09360856]
 [-0.          0.          0.98676862]
 [-0.         -0.81649658 -0.09360856]
 [-0.70710678  0.40824829 -0.09360856]]
R: 
 [[-1.41421356e+00  7.07106781e-01 -4.94974747e+00]
 [ 0.00000000e+00 -1.22474487e+00 -1.22474487e+00]
 [ 0.00000000e+00  0.00000000e+00  2.56704923e-16]]
